<?php

/** @file ...*/

/**
 * Implements hook_schema().
 */

function test_d8_schema(){

	$schema['test_d8_test_result'] = [
		'description' => 'Storing tests results',
		'fields' => [
			'trid' => [
				'type' => 'serial',
				'unsigned' => TRUE,
				'not null' => TRUE,
			],
			'uid' => [
				'description' => 'user id',
				'type' => 'int',
				'unsigned' => TRUE,
				'not null' => TRUE
			],
			'nid' => [
				'description' => 'theme id (webmaster, themer...)',
				'type' => 'int',
				'unsigned' => TRUE,
				'not null' => TRUE,
			],
			'date_start' => [
				'type' => 'int',
				'unsigned' => TRUE,
				'not null' => TRUE,
			],
			'date_end' => [
				'type' => 'int',
				'unsigned' => TRUE,
				'not null' => FALSE,
			],
			'questions_status' => [
				'type' => 'text',
				'not null' => FALSE,
				'serialize' => TRUE,
			],
			'score' => [
				'type' => 'int',
  			'size' => 'small',
				'unsigned' => TRUE,
				'not null' => FALSE,
			],
			'timer' => [
				'type' => 'int',
				'unsigned' => TRUE,
				'not null' => FALSE,
			],
		],
		/*
		'foreign keys' 	=> [
			'node_field_data' => [
				'table' => 'node_field_data',
				'columns' => ['nid' => 'nid'],
			],
			'users_field_data' => [
				'table' => 'users_field_data',
				'columns' => ['uid' => 'uid'],
			],
		],
		*/
		'primary key' => ['trid'],
	];
	return $schema;
}

