<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function test_d8_help($route_name, RouteMatchInterface $route_match){
  switch ($route_name) {
    case 'help.page.test_d8':
      $output = '';
      $output .= '<h3>'.t('About').'</h3>';
      $output .= '<p>'.t('Please send help').'</p>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function test_d8_theme($existing, $type, $theme, $path){
  return [
    'chart_tests_drupal8' => [
      'template' => 'chart-tests-drupal8',
      'variables' => ['data' => NULL]
    ],
    'timer_qcm_test_drupal8' => [
      'template' => 'timer-qcm-test-drupal8',
      'variables' => ['data' => NULL]
    ],
  ];
}

function test_d8_page_attachments(array &$page){
  $routeName = \Drupal::routeMatch()->getRouteName();
  $current_path = \Drupal::service('path.current')->getPath();

  if ($routeName == 'test_drupal8.qcm') {
    $page['#attached']['library'][] = 'test_d8/library-qcm-test-drupal8';
  }
  elseif ($current_path == '/tests-drupal8') {
    $page['#attached']['library'][] = 'test_d8/library-view-list-tests-drupal8';
  }
  elseif ($routeName == 'user.dashboard.tests') {
    $page['#attached']['library'][] = 'test_d8/library-user-dashboard-tests-drupal8';
  }
}

/*
function test_d8_views_pre_execute($view){

  $current_path = \Drupal::service('path.current')->getPath();
  // destroy session on tests landing page
  if ($current_path == '/tests-drupal8'){
    $session = \Drupal::service('user.private_tempstore')->get('test_d8');
    $session->delete('test_d8_session');
    $session->delete('session_questions');
    $session->delete('questions_list');
    $session->delete('date_start');
    $session->delete('qcm_timer');
  }

}
*/

// send settings to JS
function test_d8_preprocess_html(&$variables) {
  $settings = \Drupal::config('test_d8.settings');
  $time_to_complete_test = $settings->get('time_to_complete_test');
  $number_of_questions = $settings->get('number_of_questions');

  $variables['#attached']['drupalSettings']['TestD8']['time_to_complete_test'] = $time_to_complete_test;
  $variables['#attached']['drupalSettings']['TestD8']['number_of_questions'] = $number_of_questions;
}
